spring:
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/catalog?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: postgres
    password: admin

    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: validate


